version = 0.1
[default.deploy.parameters]
stack_name = "data-gone-60"
resolve_s3 = true
s3_prefix = "data-gone-60"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "RawDataBucketPrefix=\"datagonein60-rawdata\""
